# Formula 1 Driver Performance Intelligence

## Notebook 04: Feature Engineering

### Objective

This notebook creates new features from the existing Formula 1 driver dataset to improve machine learning performance and enhance analytical insights.

### Tasks Performed

- Load cleaned dataset
- Create derived features
- Encode categorical variables
- Scale numerical features
- Prepare final dataset for modeling

In [1]:
import pandas as pd
import numpy as np

from sqlalchemy import create_engine

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [2]:
engine = create_engine("mysql+pymysql://root:root@localhost:3306/f1")

df = pd.read_sql("SELECT * FROM drivers", engine)

df.head()

,Driver,Nationality,Seasons,Championships,Race_Entries,Race_Starts,Pole_Positions,Race_Wins,Podiums,Fastest_Laps,...,Championship Years,Decade,Pole_Rate,Start_Rate,Win_Rate,Podium_Rate,FastLap_Rate,Points_Per_Entry,Years_Active,Champion
0,Carlo Abate,Italy,"[1962, 1963]",0.0,3.0,0.0,0.0,0.0,0.0,0.0,...,NaN,1960,0.0,0.000000,0.0,0.0,0.0,0.000000,2,0
1,George Abecassis,United Kingdom,"[1951, 1952]",0.0,2.0,2.0,0.0,0.0,0.0,0.0,...,NaN,1950,0.0,1.000000,0.0,0.0,0.0,0.000000,2,0
2,Kenny Acheson,United Kingdom,"[1983, 1985]",0.0,10.0,3.0,0.0,0.0,0.0,0.0,...,NaN,1980,0.0,0.300000,0.0,0.0,0.0,0.000000,2,0
3,Andrea de Adamich,Italy,"[1968, 1970, 1971, 1972, 1973]",0.0,36.0,30.0,0.0,0.0,0.0,0.0,...,NaN,1970,0.0,0.833333,0.0,0.0,0.0,0.166667,5,0
4,Philippe Adams,Belgium,[1994],0.0,2.0,2.0,0.0,0.0,0.0,0.0,...,NaN,1990,0.0,1.000000,0.0,0.0,0.0,0.000000,1,0

In [3]:
df["Championship_Experience"] = np.where(
    df["Champion"] == True,
    "Champion",
    "Non-Champion"
)

df.head()

,Driver,Nationality,Seasons,Championships,Race_Entries,Race_Starts,Pole_Positions,Race_Wins,Podiums,Fastest_Laps,...,Decade,Pole_Rate,Start_Rate,Win_Rate,Podium_Rate,FastLap_Rate,Points_Per_Entry,Years_Active,Champion,Championship_Experience
0,Carlo Abate,Italy,"[1962, 1963]",0.0,3.0,0.0,0.0,0.0,0.0,0.0,...,1960,0.0,0.000000,0.0,0.0,0.0,0.000000,2,0,Non-Champion
1,George Abecassis,United Kingdom,"[1951, 1952]",0.0,2.0,2.0,0.0,0.0,0.0,0.0,...,1950,0.0,1.000000,0.0,0.0,0.0,0.000000,2,0,Non-Champion
2,Kenny Acheson,United Kingdom,"[1983, 1985]",0.0,10.0,3.0,0.0,0.0,0.0,0.0,...,1980,0.0,0.300000,0.0,0.0,0.0,0.000000,2,0,Non-Champion
3,Andrea de Adamich,Italy,"[1968, 1970, 1971, 1972, 1973]",0.0,36.0,30.0,0.0,0.0,0.0,0.0,...,1970,0.0,0.833333,0.0,0.0,0.0,0.166667,5,0,Non-Champion
4,Philippe Adams,Belgium,[1994],0.0,2.0,2.0,0.0,0.0,0.0,0.0,...,1990,0.0,1.000000,0.0,0.0,0.0,0.000000,1,0,Non-Champion

In [4]:
df["Wins_Per_Season"] = round(
    df["Race_Wins"] / df["Years_Active"],
    2
)

df.head()

,Driver,Nationality,Seasons,Championships,Race_Entries,Race_Starts,Pole_Positions,Race_Wins,Podiums,Fastest_Laps,...,Pole_Rate,Start_Rate,Win_Rate,Podium_Rate,FastLap_Rate,Points_Per_Entry,Years_Active,Champion,Championship_Experience,Wins_Per_Season
0,Carlo Abate,Italy,"[1962, 1963]",0.0,3.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,2,0,Non-Champion,0.0
1,George Abecassis,United Kingdom,"[1951, 1952]",0.0,2.0,2.0,0.0,0.0,0.0,0.0,...,0.0,1.000000,0.0,0.0,0.0,0.000000,2,0,Non-Champion,0.0
2,Kenny Acheson,United Kingdom,"[1983, 1985]",0.0,10.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.300000,0.0,0.0,0.0,0.000000,2,0,Non-Champion,0.0
3,Andrea de Adamich,Italy,"[1968, 1970, 1971, 1972, 1973]",0.0,36.0,30.0,0.0,0.0,0.0,0.0,...,0.0,0.833333,0.0,0.0,0.0,0.166667,5,0,Non-Champion,0.0
4,Philippe Adams,Belgium,[1994],0.0,2.0,2.0,0.0,0.0,0.0,0.0,...,0.0,1.000000,0.0,0.0,0.0,0.000000,1,0,Non-Champion,0.0

In [5]:
df["Podiums_Per_Season"] = round(
    df["Podiums"] / df["Years_Active"],
    2
)

In [6]:
df["Points_Per_Season"] = round(
    df["Points"] / df["Years_Active"],
    2
)

In [7]:
df["Win_Efficiency"] = round(
    df["Race_Wins"] / df["Race_Starts"],
    3
)

In [8]:
df["Podium_Efficiency"] = round(
    df["Podiums"] / df["Race_Starts"],
    3
)

In [9]:
df["Pole_Conversion"] = round(
    df["Race_Wins"] / df["Pole_Positions"],
    2
)

df["Pole_Conversion"] = (
    df["Pole_Conversion"]
    .replace([np.inf, -np.inf], 0)
    .fillna(0)
)

In [10]:
encoder = LabelEncoder()

df["Nationality_Encoded"] = encoder.fit_transform(
    df["Nationality"]
)

df.head()

,Driver,Nationality,Seasons,Championships,Race_Entries,Race_Starts,Pole_Positions,Race_Wins,Podiums,Fastest_Laps,...,Years_Active,Champion,Championship_Experience,Wins_Per_Season,Podiums_Per_Season,Points_Per_Season,Win_Efficiency,Podium_Efficiency,Pole_Conversion,Nationality_Encoded
0,Carlo Abate,Italy,"[1962, 1963]",0.0,3.0,0.0,0.0,0.0,0.0,0.0,...,2,0,Non-Champion,0.0,0.0,0.0,NaN,NaN,0.0,21
1,George Abecassis,United Kingdom,"[1951, 1952]",0.0,2.0,2.0,0.0,0.0,0.0,0.0,...,2,0,Non-Champion,0.0,0.0,0.0,0.0,0.0,0.0,42
2,Kenny Acheson,United Kingdom,"[1983, 1985]",0.0,10.0,3.0,0.0,0.0,0.0,0.0,...,2,0,Non-Champion,0.0,0.0,0.0,0.0,0.0,0.0,42
3,Andrea de Adamich,Italy,"[1968, 1970, 1971, 1972, 1973]",0.0,36.0,30.0,0.0,0.0,0.0,0.0,...,5,0,Non-Champion,0.0,0.0,1.2,0.0,0.0,0.0,21
4,Philippe Adams,Belgium,[1994],0.0,2.0,2.0,0.0,0.0,0.0,0.0,...,1,0,Non-Champion,0.0,0.0,0.0,0.0,0.0,0.0,3

In [11]:
scaler = StandardScaler()

scaled_columns = [
    "Race_Entries",
    "Race_Wins",
    "Podiums",
    "Points",
    "Years_Active"
]

df[scaled_columns] = scaler.fit_transform(
    df[scaled_columns]
)

df.head()

,Driver,Nationality,Seasons,Championships,Race_Entries,Race_Starts,Pole_Positions,Race_Wins,Podiums,Fastest_Laps,...,Years_Active,Champion,Championship_Experience,Wins_Per_Season,Podiums_Per_Season,Points_Per_Season,Win_Efficiency,Podium_Efficiency,Pole_Conversion,Nationality_Encoded
0,Carlo Abate,Italy,"[1962, 1963]",0.0,-0.500790,0.0,0.0,-0.192303,-0.260453,0.0,...,-0.475677,0,Non-Champion,0.0,0.0,0.0,NaN,NaN,0.0,21
1,George Abecassis,United Kingdom,"[1951, 1952]",0.0,-0.519395,2.0,0.0,-0.192303,-0.260453,0.0,...,-0.475677,0,Non-Champion,0.0,0.0,0.0,0.0,0.0,0.0,42
2,Kenny Acheson,United Kingdom,"[1983, 1985]",0.0,-0.370556,3.0,0.0,-0.192303,-0.260453,0.0,...,-0.475677,0,Non-Champion,0.0,0.0,0.0,0.0,0.0,0.0,42
3,Andrea de Adamich,Italy,"[1968, 1970, 1971, 1972, 1973]",0.0,0.113173,30.0,0.0,-0.192303,-0.260453,0.0,...,0.381529,0,Non-Champion,0.0,0.0,1.2,0.0,0.0,0.0,21
4,Philippe Adams,Belgium,[1994],0.0,-0.519395,2.0,0.0,-0.192303,-0.260453,0.0,...,-0.761412,0,Non-Champion,0.0,0.0,0.0,0.0,0.0,0.0,3

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 868 entries, 0 to 867
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Driver                   868 non-null    str
 1   Nationality              868 non-null    str
 2   Seasons                  868 non-null    str
 3   Championships            868 non-null    float64
 4   Race_Entries             868 non-null    float64
 5   Race_Starts              868 non-null    float64
 6   Pole_Positions           868 non-null    float64
 7   Race_Wins                868 non-null    float64
 8   Podiums                  868 non-null    float64
 9   Fastest_Laps             868 non-null    float64
 10  Points                   868 non-null    float64
 11  Active                   868 non-null    int64
 12  Championship Years       34 non-null     str
 13  Decade                   868 non-null    int64
 14  Pole_Rate                868 non-null    float64
 15  Start_Rate               868 non-null    float64
 16  Win_Rate                 868 non-null    float64
 17  Podium_Rate              868 non-null    float64
 18  FastLap_Rate             868 non-null    float64
 19  Points_Per_Entry         868 non-null    float64
 20  Years_Active             868 non-null    float64
 21  Champion                 868 non-null    int64
 22  Championship_Experience  868 non-null    str
 23  Wins_Per_Season          868 non-null    float64
 24  Podiums_Per_Season       868 non-null    float64
 25  Points_Per_Season        868 non-null    float64
 26  Win_Efficiency           781 non-null    float64
 27  Podium_Efficiency        781 non-null    float64
 28  Pole_Conversion          868 non-null    float64
 29  Nationality_Encoded      868 non-null    int64
dtypes: float64(21), int64(4), str(5)
memory usage: 252.5 KB

In [14]:
df.to_csv(
    "../Results/engineered_dataset.csv",
    index=False
)

print("Feature engineered dataset saved successfully!")

Feature engineered dataset saved successfully!

# Summary

New analytical features were successfully created to improve the predictive capability of machine learning models.

### Features Created

- Championship Experience
- Wins Per Season
- Podiums Per Season
- Points Per Season
- Win Efficiency
- Podium Efficiency
- Pole Conversion Rate
- Encoded Nationality
- Standardized Numerical Features

The dataset is now ready for predictive modeling.